### ISSUE TITLE
Cannot launch the windows-launcher.bat file from a directory containing space characters

### ISSUE THREAD

**Issue by Novocastrian** [openequella/openEQUELLA-admin-console-package#25]
Hi there, 

I've attempted to install the Windows launcher to the Program Files directory (C:\Program Files\Equella\ specifically), but the .bat file does not handle space characters in the file path. 

Workaround: install to a file path not containing space characters, but this is not ideal for those that like to keep all executables within the same directory.

**Comment by edalex-ian** [comment]
Fixed and released in 1.0.1.
