### ISSUE TITLE
Error launching admin console in 2019.1.1

### ISSUE THREAD

**Issue by mrblippy** [openequella/openEQUELLA-admin-console-package#26]
The error happens after you fill in your login details in the admin console launcher.

On stable.dev (running 2019.1.1) you get an `java.io.IOException: can't retrieve modification date for resource error` upon launching the admin console.

Could it maybe have something to do with the new semantic versioning change in 2019.1.1?

**Comment by PenghaiZhang** [comment]
This issue turns out to be related to the URL connections to 'Stable' start with 'http' rather than 'https'. So changing the protocol has fixed it.
