### ISSUE TITLE
Admin Console in Windows can't handle certain characters in file path

### ISSUE THREAD

**Issue by carl-edalex** [openequella/openEQUELLA-admin-console-package#39]
A client has noted that the admin console will not launch if there is an ampersand (&) in the path.  I've tested other characters and the only other ones I found were:

semicolon:   ;
caret:  ^

The error that I receive is:  Windows cannot find <path with bad character>\jdk8u242-b08-jre\bin\javaw.  Make sure you've typed the name correctly, then try again.

I think that it should be tested for non-english characters (accented characters, etc).

Thanks

**Comment by edalex-ian** [comment]
Awaiting testing.

**Comment by snehanaik22** [comment]
Test via pre-built package with following link and working as expected.
https://github.com/openequella/openEQUELLA-admin-console-package/suites/2936652416/artifacts/65970529.
