### ISSUE TITLE
Admin console fails to launch when attempting to connect to openEQUELLA over HTTPS

### ISSUE THREAD

**Issue by edalex-ian** [openequella/openEQUELLA-admin-console-package#41]
@miraboureslan originally opened this in issue openequella/openequella.github.io#82

I quote:

> we are running openequella with proxy for SSL
> we can access the institution without any errors but cant access the administration console
> port used:8443
> when connect to the admin console we reach the popup to enter username and password
> after that the jars the should be located in the cache folder are not getting downloaded
> to the launcher doesnot display anything and we can see in the task manager that it is still running

**Comment by edalex-ian** [comment]
Heya @miraboureslan 

Thanks for taking to the time to reach out.

To really help I'll need a bit more information from you. Could you please advise on the following:

1. What operating system are you on?
2. What version of the Admin Console Package are you using?
3. What version of openEQUELLA are you running?
4. Could you please share with me the URL you're attempting to use? (Feel free to replace hostname/domain for privacy - just let me know if you do.)
5. Are you using an unusual CA for your HTTPS certificate (or possibly testing with a self signed certificate)?

Personally, I just downloaded the latest version (1.1.0) of the console package for Linux and tested against openEQUELLA 2020.2 running with a certificate issued by Let's Encrypt CA and all is working.

**Comment by miraboureslan** [comment]
thank you for your help
we are using admin-console-package-for-windows-v1.1.0
and equella 2020.2.0
this is the url we are using for the institution: https://lor-stg.medad.com/medad/
we are running equella as docker container, we got the docker file from git (https://github.com/openequella/openEQUELLA/tree/develop/docker)
our problem is that when we try to connect to the admin console after entering the username and password the following error is thrown:
Exception in thread "main" java.lang.RuntimeException: org.springframework.remoting.RemoteAccessException: Could not access HTTP invoker remote service at [https://lor-stg.medad.com/medad/invoker/com.tle.core.remoting.RemotePluginDownloadService.service]; nested exception is java.io.IOException: Did not receive successful HTTP response: status code = 401, status message = [null]

thankx in advance

**Comment by edalex-ian** [comment]
Heya @miraboureslan 

My attention is drawn to the `status code = 401`. This makes me wonder if the credentials you're providing when "entering the username and password" are correct. You probably want to try with `TLE_ADMINISTRATOR` and the same credentials you're using to login into the institution (not the server admin page) via https://lor-stg.medad.com/medad/. Is that what you're doing?

**Comment by miraboureslan** [comment]
hello,
yes for sure we are using the TLE_ADMINISTRATOR
our issue is when we run the openequella using SSL(Let's Encrypt CA) note that we are on cloudflare
please can you give us how should we run SSL maybe we are adding the certificate in the wrong place.
Do we need to add it through reverse proxy, haproxy or directly on the openequella tomcat
i feel we are getting blocked somewhere

**Comment by edalex-ian** [comment]
Okay then, two parts (optionally a third):

1. Seeing you're reporting you're seeing a 401 message, that is a message which is being returned from the server. This implies you are successfully communicating with the server across SSL - otherwise you would not be able to get _any_ HTTP status code. So in theory, SSL is all working fine; however
2. If you do wish to add custom certs (which, I don't think you need to do for Let's Encrypt - but in case you do) then you need to add it to the certificate store of the JRE which is bundled with the admin console package. You can follow the general online instructions for this, however you need to know that the certificate store is located at `admin-console-package-for-linux-v1.1.0/jdk8u242-b08-jre/lib/security`; and lastly
3. If the issue still persists, I think a video screen capture may be the best way forward to really see this in action.

As an aside, I'm wondering whether cloud-flare could be doing something undesirable. If you have a option of a simple SSL reverse proxy or an AWS load balancer than that may help rule that out.

**Comment by SammyIsConfused** [comment]
heya @miraboureslan,
I've updated the README.md with a way to add Root CA certificates to your admin-console-package - if you follow those instructions does it fix your issue?

**Comment by miraboureslan** [comment]
thank you for your help
it worked
the issue was where to put the certificate
when we added certificate on tomcat as reverse proxy it worked

**Comment by edalex-ian** [comment]
Excellent, great to hear @miraboureslan . :+1:
