### ISSUE TITLE
openEQUELLA language preferences

### ISSUE THREAD

**Issue by miraboureslan** [openequella/openEQUELLA-admin-console-package#43]
hello,
is there a way to change language preferences for a user other than from my preferences page
i need to add a language switcher on the navigation bar for all pages.
 is there a way to do this?
also i need when user comes from my site to equella to have the language persistent for example if he/she in moodle are on arabic and go to openequella need to load the arabic lang packs
thankx in adnvace

**Comment by edalex-ian** [comment]
Hi @miraboureslan 

This query is more related to the server and as such would be better placed over on the main repo at [openequella/openEQUELLA](https://github.com/openequella/openEQUELLA). However, being that it's not so much an issue or feature request, probably best to reach out on the user group @ https://groups.google.com/a/apereo.org/g/equella-users

Cheers.

P.S. Personally I've not come across this before, you could possibly do it with the scripting API (but even then it'd be changing it for a specific user - so if you need this for 'guest' user it may not be suitable).
